[package]
authors = ["picoCTF team <opensource@picoctf.org>"]
description = "OCI runtime wrapper for modifying container configs before creation"
edition = "2021"
license = "MIT"
name = "oci-interceptor"
publish = false
repository = "https://github.com/picoCTF/oci-interceptor"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.23", features = ["cargo"] }
oci-spec = "0.5.8"
