[package]
name = "oci-interceptor"
version = "0.1.0"
edition = "2021"
description = "OCI runtime wrapper for modifying container configs before creation"
authors = ["picoCTF team <opensource@picoctf.org>"]
repository = "https://github.com/picoCTF/oci-interceptor"
license = "MIT"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.55"
clap = { version = "3.1.6", features = ["cargo"] }
oci-spec = "0.5.5"
